services:
  db:
    image: postgres:16
    container_name: miniavia-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  migrate:
    image: migrate/migrate:4
    container_name: miniavia-migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./internal/migrations:/migrations:ro
    command: >
      -path=/migrations
      -database ${DATABASE_URL}
      up
    restart: "no"
    env_file:
      - .env

  api:
    platform: ${PLATFORM:-linux/arm64}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miniavia-api
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    restart: unless-stopped

volumes:
  pgdata:
